#!/usr/bin/env python3

if __name__ == '__main__':
    import sys
    import hello as h

    who = "world"
    option = ""
    message = ""

    if len(sys.argv) > 2:
        option = sys.argv[1]
        who = sys.argv[2]
    elif len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
            option = sys.argv[1]
        else:
            who = sys.argv[1]

    message = "Hello " + who + "!"

    try:
        if option == "-mu":
            h.print_multi(message)
        elif option == "-c":
            h.print_color(message)
        elif option == "-a":
            h.print_ascii(who)
        elif option == "-me":
            h.print_merica(message)
        elif option == "-st":
            h.print_strawberry(message)
        elif option == "-se":
            h.print_searchbar(who)
        elif option == "-h":
            h.print_heart(who)
        else:
            h.print_plain(message)
    except KeyboardInterrupt:
        exit()
